name: Update Demanda
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: update data
        run: |
          python update/update_demanda.py
      - name: commit
        run: |
          git pull
          git add -A
          git commit -m "[ci] actualización demanda"
          git push -q "https://$GH_TOKEN@github.com/pr0nstar/despacho_de_carga.git" main
