name: Update Demanda
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: write

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: update data
        run: |
          python update/update_demanda.py
      - name: git status
        id: git-status
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [ -z "$(git status --porcelain)" ]; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          fi
      - name: commit
        if: steps.git-status.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "[ci] actualización demanda"
          git push origin HEAD:main
